(part "LP2985IM5-2_7_NOPB"
    (packageRef "SOT95P280X145-5N")
    (interface
        (port "1" (symbPinId 1) (portName "IN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "ON/OFF") (portType INOUT))
        (port "4" (symbPinId 4) (portName "BYPASS") (portType INOUT))
        (port "5" (symbPinId 5) (portName "OUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "926-2985IM5-2.7/NOPB")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/LP2985IM5-27-NOPB?qs=7lkVKPoqpbaBU6JCbe3gTQ%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "LP2985IM5-2.7/NOPB")
    (property "Description" "Texas Instruments LP2985IM5-2.7/NOPB, Low Noise LDO Voltage Regulator, 350mA, 2.7 V 1%, 2.2  16 Vin, 5-Pin")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/lp2985-n")
    (property "symbolName1" "LP2985IM5-2_7_NOPB")
)
